name: Data Engineering CI
on:
    push:
        branches:
            - main
            - feat/*
            - fix/*

jobs:
    run-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.12

            - name: Install dependencies
              run: |
                pip install mypy==1.7.1 pylint==3.0.2 pyspark==3.3.0 coverage

            - name: Type check
              run: mypy ./ --ignore-missing-imports

            - name: Lint
              run: pylint app/ main.py setup.py

            - name: Testing
              run: coverage run --source=app -m unittest discover -s app/tests/

            - name: Test coverage report
              run: coverage report
