name: Data Engineering CI
on:
    push:
        branches:
            - main
            - feat/*
            - fix/*

jobs:
    run-ci:
        runs-on: ubuntu-latest
        container: vighneshwed/glue3.0:latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Glibc6
              run: |
                sudo apt update
                sudo apt install libc6

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"

            - name: Check current repo
              if: always()
              run: |
                whoami
                pwd
                ls -a

            - name: Install dependencies
              if: always()
              run: |
                python3 -m pip install --upgrade pip
                python3 -m pip install -r requirements.txt

            - name: Install dependencies
              if: always()
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt

            - name: Type check
              run: mypy ./ --ignore-missing-imports

            - name: Lint
              run: pylint app tests main.py setup.py --output pylint-report.txt

            - name: Testing
              run: coverage run --source=app -m unittest discover -s tests

            - name: Test coverage report
              run: |
                coverage report
                coverage xml

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              with:
                args: >
                  -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

            - uses: sonarsource/sonarqube-quality-gate-action@master
              timeout-minutes: 5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
