name: Data Engineering CI
on:
    push:
        branches:
            - main
            - feat/*
            - fix/*

jobs:
    run-ci:
        runs-on: ubuntu-latest
        container: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.12

            - name: Install dependencies
              run: |
                pip install mypy==1.7.1 pylint==3.0.2 pyspark==3.3.0 coverage

            - name: Type check
              run: mypy ./ --ignore-missing-imports

            - name: Lint
              run: pylint app/ main.py setup.py  --output pylint-report.txt

            - name: Testing
              run: coverage run --source=app -m unittest discover -s app/tests/

            - name: Test coverage report
              run: coverage xml
    
            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              with:
                args: >
                  -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
            - uses: sonarsource/sonarqube-quality-gate-action@master
              timeout-minutes: 5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
