name: Download and Upload to S3

on:
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Download Dataset from Kaggle
        run: |
          kaggle datasets download -d mastmustu/insurance-claims-fraud-data
          unzip -q insurance-claims-fraud-data.zip -d dataset

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@v1.3.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "glue-bucket-vighnesh"
          source_dir: 'dataset'
          
